spring.application.name=readin-backend
spring.datasource.url=jdbc:mariadb://${MYSQLHOST:db}:${MYSQLPORT:3306}/${MYSQLDATABASE:readin}?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:asdf1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect



# File upload configuration
file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
